import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ResearchActionProvider } from "@/app/contexts/ResearchActionContext";
import ResearchActionModal from "@/app/components/ResearchActionModal";
import { AuthProvider } from "@/providers/auth";
import { Toaster } from "react-hot-toast";
import { ResearchProvider } from "@/app/contexts/ResearchContext";
import ResearchInitializer from "@/app/components/ResearchInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ResearchActionProvider>
            <ResearchProvider>
              <ResearchInitializer />
              {children}
              <ResearchActionModal />
              <Toaster />
            </ResearchProvider>
          </ResearchActionProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
