import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ResearchLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex w-full">
      <Sidebar />
      <main className="flex w-full">
        <div className="hidden lg:block lg:w-[20%]"></div>
        <div className="w-full lg:w-[80%]">{children}</div>
      </main>
    </div>
  );
}
